symphart/src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BookRepository::class)
 */
class Book
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $isbn;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;


    /**
     * @ORM\Column(type="string", length=4)
     */
    private $publish_date;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image_path;

    /**
     * @ORM\Column(type="text", nullable=true, options={"default" : ""})
     */
    private $notes;

    /**
     * @ORM\ManyToMany(targetEntity=Author::class, inversedBy="books")
     */
    private $author;

    public function __construct()
    {
        $this->author = new ArrayCollection();
    }


    public function __toString()
    {
        return (string) $this->name;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getPublishDate(): string
    {
        return $this->publish_date;
    }

    public function setPublishDate(string $publish_date): self
    {
        $this->publish_date = $publish_date;

        return $this;
    }

    public function getImagePath(): ?string
    {
        return $this->image_path;
    }

    public function setImagePath(?string $image_path): self
    {
        $this->image_path = $image_path;

        return $this;
    }

    public function getISBN(): ?string
    {
        return $this->isbn;
    }

    public function setISBN(?string $isbn): self
    {
        $this->isbn = $isbn;

        return $this;
    }

    public function getNotes(): ?string
    {
        return $this->notes;
    }

    public function setNotes(?string $notes): self
    {
        $this->notes = $notes;

        return $this;
    }

    /**
     * @return Collection<int, Author>
     */
    public function getAuthor(): Collection
    {
        return $this->author;
    }

    public function addAuthor(Author $author): self
    {
        if (!$this->author->contains($author)) {
            $this->author[] = $author;
        }

        return $this;
    }

    public function removeAuthor(Author $author): self
    {
        $this->author->removeElement($author);

        return $this;
    }

}

symphart/src/Controller/BookController.php
<?php
// src/Controller/BookController.php

namespace App\Controller;

use App\Entity\Book;
use App\Repository\BookRepository;
use Doctrine\ORM\EntityManagerInterface;
//use for routes
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

use Doctrine\Persistence\ManagerRegistry;

// form controls
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

// request, response
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;


class BookController extends AbstractController {
    // registry manager
    private $manager_registry;
    private $bookRepository;
    private $entityManager;

    public function __construct(
        EntityManagerInterface $entityManager,
        ManagerRegistry $manager_registry,
        BookRepository $bookRepository
    )
    {
        $this->manager_registry = $manager_registry;
        $this->bookRepository = $bookRepository;
        $this->entityManager = $entityManager;
    }

    /**
     * @Route("/books", name="books_list")
     */
    public function list(){
        $books = $this->entityManager->getRepository(Book::class)->findAll();
        return $this->render('books/index.html.twig', array('books' => $books));
    }

    /**
     * @Route("/book/edit/", name="book_edit")
     */
    public function edit(Request $request, int $id){
        dd($request);
    }

    /**
     * @Route("/book/{id}", name="book_show")
     */
    public function show(Request $request, int $id): Response
    {
        $book = $this->manager_registry->getRepository(Book::class)->find($id);
        $authors = $this->bookRepository->findAuthorsByBook($id);

        return $this->render('books/show.html.twig', array('book' => $book, 'authors' => $authors));
    }

    /**
     * @Route("/book/delete/", name="book_delete")
     */
    public function delete(Request $request, int $id)
    {
        dd($request);
    }

    /**
     * @Route("/book/new/", name="book_new")
     */
    public function new()
    {
        dd(array());
    }

}

symphart/templates/books/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Book{% endblock %}

{% block body %}
    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
    <hr>
    <a href="/books">Go Back</a>
{% endblock %}

symphart/templates/books/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}SymfoElik Books{% endblock  %}

{% block body %}
    {% if books %}
        <h3>Books List</h3>
        <table id="books" class="table table-striped">
            <tbody>
                {% for book in books %}
                <tr>
                    <td>
                        <a href="/book/{{ book.id }}">
                            <img style="width: 90px; height: auto;" src="{{ book.imagePath }}">
                        </a>
                    </td>

                    <td>
                        <a href="/book/{{ book.id }}">{{ book.title }}</a>
                    </td>

                    <td>
                        <a href="/book/{{ book.id }}">{{ book.publishDate }}</a>
                    </td>

                    <td>
                        <a href="/book/{{ book.id }}">{{ book.isbn }}</a>
                    </td>


                    <td class="row__align--end">
                        <a href="/book/{{ book.id }}" class="btn btn-info">Show</a>
                        <a href="/book/edit/{{ book.id }}" class="btn btn-light">Edit</a>
                        <a href="javascript:void(0)" class="btn btn-danger delete-book" data-id="{{ book.id }}">Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No books to display</p>
    {% endif %}
        <a href="/book/new" class="btn btn-primary">New Book</a>
{% endblock  %}
{% block javascript %}
        <script src="/js/books.js"></script>
{% endblock  %}

symphart/templates/books/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Book{% endblock %}

{% block body %}
    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
    <hr>
    <a href="/">Go Back</a>
{% endblock %}

symphart/templates/books/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ book.title }}{% endblock %}

{% block body %}

    <div class="card" style="width: 18rem; margin: auto;">
        <img class="card-img-top" src="{{book.imagePath}}" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">{{book.title}}</h5>
            <p class="card-text">{{ book.notes }}</p>
            {% if authors %}
                {% if authors|length > 1 %}
                    {% set text = 'Authors'%}
                {% else %}
                    {% set text = 'Author'%}
                {% endif %}

                <p class="card-text">{{ text }}:</p>

                {% for author in authors %}
                    <a href="/author/{{ author['author_id'] }}">{{ author['first_name'] ~ ' ' ~ author['last_name']}}</a>
                {% endfor %}

            {% else %}
                <p class="card-text">Not found authors for this book.</p>
            {% endif %}
        </div>
    </div>

    <hr>
    <a href="/books">Back to Books List</a>
{% endblock %}