symphart/src/Entity/Author.php
<?php

namespace App\Entity;

use App\Repository\AuthorRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AuthorRepository::class)
 */
class Author
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $last_name;

    /**
     * @ORM\Column(type="integer", nullable=true, options={"default" : 0})
     */
    private $books_count;

    /**
     * @ORM\Column(type="string", length=255, nullable=true, options={"default" : 0})
     */
    private $notes;

    /**
     * @ORM\ManyToMany(targetEntity=Book::class, mappedBy="author")
     */
    private $books;

    public function __construct()
    {
        $this->books = new ArrayCollection();
    }

    public function __toString()
    {
        return (string) $this->name;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getNotes(): ?string
    {
        return $this->notes;
    }

    public function setNotes(?string $notes): self
    {
        $this->notes = $notes;

        return $this;
    }

    public function getBooksCount(): ?int
    {
        return $this->books_count;
    }

    public function setBooksCount(?int $books_count): self
    {
        $this->books_count = $books_count;

        return $this;
    }

    /**
     * @return Collection<int, Book>
     */
    public function getBooks(): Collection
    {
        return $this->books;
    }

    public function addBook(Book $book): self
    {
        if (!$this->books->contains($book)) {
            $this->books[] = $book;
            $book->addAuthor($this);
        }

        return $this;
    }

    public function removeBook(Book $book): self
    {
        if ($this->books->removeElement($book)) {
            $book->removeAuthor($this);
        }

        return $this;
    }

}

symphart/src/Controller/AuthorController.php
<?php
namespace App\Controller;

use App\Entity\Author;
use App\Repository\AuthorRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;

class AuthorController extends AbstractController {
    private $authorRepository;
    private $entityManager;

    public function __construct(
        AuthorRepository $authorRepository,
        EntityManagerInterface $entityManager
    )
    {
        $this->authorRepository = $authorRepository;
        $this->entityManager = $entityManager;
    }

    /**
     * @Route("/authors", name="author_list")
     * @Method({"GET", "POST"})
     */
    public function index(AuthorRepository $authorRepository, Request $request)
    {
        if($request->query->get('q')){
            $authors = $authorRepository->findAuthorByAnyField($request->query->get('q'));
        }else{
            $repository = $this->entityManager->getRepository(Author::class);
            $authors = $repository->findAll();
        }

        return $this->render('authors/index.html.twig', array('authors' => $authors));
    }

    /**
     * @Route("/author/edit/{id}", name="edit_author")
     * @Method({"GET", "POST"})
     */
    public function edit(Request $request, $id)
    {
        $author = new Author();
        $author = $this->entityManager->getRepository(Author::class)->find($id);

        $form = $this->createFormBuilder(($author))
            ->add(
                'firstName',
                TextType::class,
                array('attr' => array('class' => 'form-control'))
            )
            ->add(
                'lastName',
                TextType::class,
                array('attr' => array('class' => 'form-control'))
            )
            ->add(
                'notes',
                TextareaType::class,
                array(
                    'attr' => array(
                                'class' => 'form-control',
                                'style' => 'height: 130px',
                                'maxLength' => "255"
                            )
                )
            )

            ->add(
                'save',
                SubmitType::class,
                array(
                    'label' => 'Update',
                    'attr' => array('class' => 'btn btn-primary mt-3')
                )
            )
            ->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $this->entityManager->flush();

            return $this->redirectToRoute('author_list');
        }

        return $this->render(
            'authors/edit.html.twig',
            array('form' => $form->createView())
        );
    }


    /**
     * @Route("/author/delete/{id}")
     * @Method({"DELETE"})
     */
    function delete($id)
    {
        $author = $this->doctrine->getRepository(Author::class)->find($id);

        $entityManager = $this->doctrine->getManager();
        $entityManager->remove($author);
        $entityManager->flush();

        $response = new Response();
        $response->send();
    }


    /**
     * @Route("/author/{id}", name="author_show")
     * @Method({"GET"})
     */
    public function show($id)
    {
        $author = $this->entityManager->getRepository(Author::class)->find($id);
        $books = $this->authorRepository->findBooksByAuthor($id);

        return $this->render('authors/show.html.twig', array('author' => $author, 'books' => $books));
    }
}

symphart/templates/authors/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Author{% endblock %}

{% block body %}
    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
    <hr>
    <a href="/authors">Go Back</a>
{% endblock %}

symphart/templates/authors/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}SymfoElik Authors{% endblock  %}

{% block body %}
    {% if authors %}
        <h3>Authors List</h3>
        <form id="searchForm" action="{{ path('author_list')}}">
            <input type="search"
                id="searchBtn"
                name="q"
                class="form-control"
                placeholder="Search by any field ..."
                aria-label="Search"
                value="{{ app.request.query.get('q') }}"
            >
        </form>
        <table id="authors" class="table table-striped">
            <tbody>
                {% for author in authors %}
                {% set author_notes = (author.notes|length > 20) ? author.notes|slice(0,17) ~ '...' : author.notes %}
                {% set notes_tooltip = author.notes %}

                <tr>
                    <td>
                        <a href="/author/{{ author.id }}">{{ (author.firstName ~ ' ' ~ author.lastName)|title }}</a>
                    </td>
                    <td>
                        <span
                            class="d-inline-block"
                            tabindex="0"
                            data-toggle="tooltip"
                            title="{{ notes_tooltip }}"
                        >
                            {{ author_notes }}
                        </span>
                    </td>
                    <td>{{ author.booksCount }}</td>
                    <td class="row__align--end">
                        <a href="/author/{{ author.id }}" class="btn btn-info">Show</a>
                        <a href="/author/edit/{{ author.id }}" class="btn btn-light">Edit</a>
                        <a href="javascript:void(0)" class="btn btn-danger delete-author" data-id="{{ author.id }}">Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No authors to display</p>
    {% endif %}
        <a href="/author/new" class="btn btn-primary">New Author</a>
{% endblock  %}
{% block javascript %}
        <script src="/js/author.js"></script>
{% endblock  %}

symphart/templates/authors/show.html.twig
{% extends 'base.html.twig' %}

{% set author_fullname = (author.firstName ~ ' ' ~ author.LastName)|title %}

{% block title %}{{ author_fullname }}{% endblock %}

{% block body %}

    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">{{ author_fullname }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">
                Books: {{ books|length }}
            </h6>

            <p class="card-text">{{ author.notes }}</p>
            {% if books %}
                {% for book in books %}
                    <p>
                        <a href="/book/{{ book['book_id']}}" class="card-link">{{ book['title']}}</a>
                    </p>
                {% endfor %}

            {% else %}

            {% endif %}

            <a href="/author/edit/{{ author.id }}" class="card-link">Edit</a>
        </div>
    </div>

    <hr>
    <a href="/authors">Back to Authors List</a>
{% endblock %}